doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
#        'alexinbox80\StudentsSalesBundle\DoctrineMigrations' : '%kernel.project_dir%/vendor/alexinbox80/students-sales-bundle/migrations'
    enable_profiler: false
